# Generated by Django 4.1 on 2023-06-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('project_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=100)),
                ('project_slug', models.SlugField(max_length=100)),
                ('project_description', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
