# Generated by Django 4.1 on 2023-06-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taigas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('project_id', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('project_slug', models.SlugField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='DropshipUser',
        ),
    ]
