# Generated by Django 4.1 on 2023-06-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taigas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
