# Generated by Django 4.1 on 2023-06-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taigas', '0002_account_delete_dropshipuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
