# Generated by Django 4.1 on 2023-06-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taigas', '0003_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
