# Generated by Django 4.1 on 2023-06-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taigas', '0004_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='project_description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='project_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
